### ISSUE TITLE
Relicense repo

### ISSUE THREAD

**Issue by iliana** [wobscale/config#10]
We're probably going to start writing actual code for the PeeringDB Ansible module that we're planning in #5.

I'd like to propose relicensing as one of the GPLs and adding the SPDX-License-Identifier to each file in the repo.

cc @euank @LinuxMercedes

**Comment by LinuxMercedes** [comment]
I'm not opposed to GPLing these configs, but we may not be in a position to be able to legally do so. As I understand it, the CC0 is not like most licenses because it, to the fullest extent possible under law, places the work in the public domain. This cannot be un-done, so unless we make extensive changes to the files here, we might be stuck with CC0, at least for what exists currently.

**Comment by iliana** [comment]
We can change the license whenever we want, but folks can use *those* versions under the CC0. Newer changes would be licensed only under the newer license.

(not a lawyer blah blah blah)

**Comment by LinuxMercedes** [comment]
I think that makes sense!

In that case, uhhhh, GPLv3? Or are you thinking AGPL?

**Comment by iliana** [comment]
Either, I don't think it makes much sense to license giant piles of YAML as AGPL but any actual code we write should probably do that.

**Comment by euank** [comment]
My opinion is GPLv3 for now because ansible yaml isn't really a network accessible service.

We'll deal with the future if/when the future is network accessible.
